.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. bitnamicoin_qt test_bitnamicoin_qt
clean: FORCE
	$(MAKE) -C .. bitnamicoin_qt_clean test_bitnamicoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_bitnamicoin_qt_check
bitnamicoin-qt bitnamicoin-qt.exe: FORCE
	 $(MAKE) -C .. bitnamicoin_qt
